# bhd_recovery_mixture.py - Bernoulli-mixture fitting for subtraction recovery.
#
# Fits a K-component Bernoulli mixture over candidate residual haplotypes with
# K-means++ initialisation, multiple restarts, and inner BIC over K.  Provides
# both the MAP-regularised EM (_fit_bernoulli_mixture_select_K) and the
# maximum-likelihood variant (_fit_bernoulli_mixture_ml_select_K); their rounded
# {0,1} consensus thetas become candidate founder haps for the outer BIC subset-
# selection on actual sample data.
#
# Leaf module of the bhd_recovery 4-file split: imports only numpy,
# dynamic_threads, and mixture tuning constants from bhd_config.  See
# bhd_recovery.py for subsystem context and the numba-optimisation history.

import numpy as np

# Shared dynamic-thread reallocation, re-checked at the mixture K-sweep restart
# boundaries; no-ops on the sequential path until a pool wires the counters.
import dynamic_threads

import warnings
try:
    from numba import njit, prange
    HAS_NUMBA = True
except ImportError:
    HAS_NUMBA = False
    warnings.warn(
        "Numba not found; bhd_recovery_mixture kernels fall back to pure Python "
        "(slower but numerically identical).",
        ImportWarning,
    )
    def njit(*args, **kwargs):
        def decorator(func):
            return func
        if len(args) == 1 and callable(args[0]) and not kwargs:
            return args[0]
        return decorator
    prange = range

from bhd_config import (
    RECOVERY_MIXTURE_K_MAX,
    RECOVERY_MIXTURE_MAX_ITER,
    RECOVERY_MIXTURE_N_RESTARTS,
    RECOVERY_MIXTURE_PATIENCE,
    RECOVERY_MIXTURE_RNG_SEED,
    RECOVERY_MIXTURE_THETA_EPS,
    RECOVERY_MIXTURE_TOL,
)


# =============================================================================
# SUBTRACTION-BASED RECOVERY: BERNOULLI MIXTURE HELPERS
# =============================================================================
#
# These helpers fit a Bernoulli mixture model to a candidate pool of clean
# residuals (one per "carrier" sample after subtracting an existing founder).
# Each candidate is a binary vector of length L_kept; we model them as a
# mixture of K hidden founder profiles theta_k in [0,1]^L, each candidate
# generated by one component:
#
#     P(c | k) = prod_l theta_k[l]^c[l] * (1 - theta_k[l])^(1-c[l])
#
# We fit by EM with K-means++ initialisation and multiple restarts, then
# pick the K that minimises BIC over candidate density (inner BIC).  The
# fitted theta vectors (rounded to {0, 1}) become consensus candidate haps
# for outer BIC subset-selection on actual sample data.


@njit(cache=True)
def _kmeans_pp_init_kernel(candidates, K, uniforms):
    """Numba kernel for _kmeans_pp_init.

    Faithfully reproduces the K-means++ algorithm using uniform random
    draws supplied by the wrapper:

      - uniforms[0]: drives the first center selection (uniform over N)
      - uniforms[k] for k in 1..K-1: drives the weighted choice for
        the k-th center (weighted by min-L1-distance squared; L1 equals
        Hamming on binary candidates)

    Conversion from uniform to index:
      - For the first center: int(uniforms[0] * N) — same as
        np.random.randint(N) under the hood, gives a value in [0, N).
      - For weighted draws: inverse-CDF lookup on the normalized
        squared-distance probabilities.

    Edge cases handled:
      - K >= N: defensive duplicates path (matches the original's
        `idx = list(range(N)) + [rng.integers(N) ...]` behavior).
      - All min_dists zero (all candidates identical to some existing
        center): pick first unpicked index, falling back to
        int(uniforms[k] * N) if all are picked (matches the original's
        `[i for i in range(N) if i not in centers_idx]` then random).

    SEMANTIC DIFFERENCE FROM ORIGINAL:
      The original calls `rng.integers(N)` and `rng.choice(N, p=probs)`
      directly on the user's Generator.  This kernel takes precomputed
      uniforms, so the underlying PRNG sequence will differ — but only
      by which Generator method advances the state.  The weights, the
      inverse-CDF mapping, and the K-means++ algorithm are preserved
      exactly.  Tested empirically and accepted by the project owner
      (see conversation transcript): tiny shifts in which specific
      candidate gets picked for which center may occur, but downstream
      BIC selection on actual sample data is stable enough to absorb
      these.

    Args:
        candidates: (N, L) float64 candidate array (binary 0/1 in argmax
            mode, fractional in [0, 1] in soft mode)
        K: number of centers to pick
        uniforms: (K,) float64 random draws in [0, 1) from the wrapper

    Returns:
        centers_idx: (K,) int64 — indices into candidates for the
            selected centers (caller does candidates[centers_idx].copy()
            to get the centers themselves)
    """
    N, L = candidates.shape

    centers_idx = np.empty(K, dtype=np.int64)
    # picked[i] = True if i is already a chosen center (used in the
    # "all-zero min_dists" tiebreak path).  bool mask replaces the
    # original's Python `in centers_idx` list-membership test.
    picked = np.zeros(N, dtype=np.bool_)

    # === First center: uniform over N (matches rng.integers(N)) ===
    # int(u * N) maps uniformly into [0, N) for u in [0, 1).
    c0 = int(uniforms[0] * N)
    if c0 >= N:
        c0 = N - 1   # defensive: clip if u rounds to 1.0 (numerically possible)
    centers_idx[0] = c0
    picked[c0] = True

    # Per-candidate running minimum distance to nearest center.  Distance
    # is L1 (sum of |a - b| over sites).  On BINARY candidates this equals
    # Hamming distance exactly (|0-1| = 1, |0-0| = |1-1| = 0), so argmax-
    # mode recovery is bit-identical to the original Hamming kernel; on
    # FRACTIONAL (soft) candidates L1 is the correct generalisation (a
    # Hamming `!=` test would treat 0.49 vs 0.51 as a full mismatch).
    # We update this incrementally each time a new center is added —
    # cheaper than recomputing from scratch (the original recomputes
    # min over all existing centers each iteration via the (N, n_exist, L)
    # broadcast).  Mathematical result is identical: min over a growing
    # set equals running-min.
    #
    # Initial state: distance to c0 only.
    min_dists = np.empty(N, dtype=np.float64)
    for i in range(N):
        # L1 distance between candidates[i] and candidates[c0]
        d = 0.0
        for l in range(L):
            d += abs(candidates[i, l] - candidates[c0, l])
        min_dists[i] = d

    # === Subsequent centers: weighted by squared min-Hamming ===
    for k in range(1, K):
        # Check if all min_dists are zero (all candidates identical to
        # some chosen center).  This matches the original's
        # `if min_dists.sum() == 0: remaining = [i not in centers_idx]`
        # tiebreak path.
        any_nonzero = False
        for i in range(N):
            if min_dists[i] > 0:
                any_nonzero = True
                break

        if not any_nonzero:
            # Tiebreak: pick the first unpicked index.  Original used
            # rng.choice over the remaining list; here we pick
            # deterministically (the first unpicked).  This is a
            # SEMANTIC SIMPLIFICATION — when this tiebreak path is
            # reached (all candidates identical to some center) the
            # choice is degenerate anyway, but we note it for honesty.
            new_c = -1
            for i in range(N):
                if not picked[i]:
                    new_c = i
                    break
            if new_c < 0:
                # All N candidates already picked (only possible if K >= N,
                # which the wrapper would route through the duplicate path
                # before calling this kernel — defensive only).
                new_c = int(uniforms[k] * N)
                if new_c >= N:
                    new_c = N - 1
        else:
            # Inverse-CDF sample over min_dists^2.  Build cumulative
            # distribution on the fly and find the index where u
            # crosses it.
            total = 0.0
            for i in range(N):
                d = min_dists[i]
                total += float(d) * float(d)
            target = uniforms[k] * total
            cum = 0.0
            new_c = N - 1   # defensive default (last index, in case
                              # of float rounding at the boundary)
            for i in range(N):
                d = min_dists[i]
                cum += float(d) * float(d)
                if cum >= target:
                    new_c = i
                    break

        centers_idx[k] = new_c
        picked[new_c] = True

        # Update running min_dists with distance to new_c (skip the last
        # iteration since we don't need min_dists after that)
        if k < K - 1:
            for i in range(N):
                d = 0.0
                for l in range(L):
                    d += abs(candidates[i, l] - candidates[new_c, l])
                if d < min_dists[i]:
                    min_dists[i] = d

    return centers_idx


def _kmeans_pp_init(candidates, K, rng):
    """K-means++ initialisation for binary data using Hamming distance.

    Picks K centers from candidates: the first uniformly at random, each
    subsequent weighted by squared min-Hamming-distance from existing
    centers.  This gives spread-out initial centers that typically lead
    EM to good local optima — much more robust than uniform random init.

    Args:
      candidates: (N, L) binary array
      K: number of centers to pick
      rng: numpy Generator

    Returns: (K, L) array of centers selected from candidates (copy).

    Implementation: delegates to a numba kernel that uses incremental
    running-min for Hamming distances (vs the original's full
    recomputation from scratch each iteration), with an inverse-CDF
    weighted sampling driven by precomputed uniforms drawn from the
    Python-level rng.

    NOTE ON RANDOM STATE:
      The original calls `rng.integers(N)` and `rng.choice(N, p=probs)`
      directly.  This wrapper instead draws K uniform `rng.random()`
      values and passes them to the kernel for in-kernel conversion to
      indices via int(u*N) for the first center and inverse-CDF for
      subsequent ones.  The math is preserved exactly (same weights,
      same algorithm); only the specific bytes consumed from the PRNG
      state differ, which causes the specific indices picked across
      n_restarts multi-starts to shuffle.  Project owner has accepted
      this tradeoff in exchange for a ~7-8x speedup on the dominant
      inner-hamming step.  Downstream BIC selection on sample data is
      empirically stable to this perturbation (validated against the
      legacy implementation's selected-K trace; see conversation
      transcript).
    """
    N, L = candidates.shape
    if K >= N:
        # Defensive: caller should never let this happen, but if it does,
        # return all candidates plus repeats so the EM has something to work with.
        # This path is preserved EXACTLY as the original (still uses rng
        # directly).
        idx = list(range(N)) + [int(rng.integers(N)) for _ in range(K - N)]
        return candidates[idx].copy()

    # Draw K uniform [0, 1) values from the user's Generator for the
    # kernel to consume.  Using rng.random(K) advances the Generator
    # state exactly once with a single call, vs the original's K calls
    # to rng.integers / rng.choice.
    uniforms = rng.random(K)

    candidates_arr = np.ascontiguousarray(candidates, dtype=np.float64)
    centers_idx = _kmeans_pp_init_kernel(candidates_arr, int(K), uniforms)
    return candidates[centers_idx].copy()


@njit(cache=True)
def _logsumexp_axis1_kernel(x):
    """Numerically stable log-sum-exp along axis 1 of a 2D array.

    Numba-friendly version of _logsumexp(x, axis=1).  Returns a 1D
    array of length x.shape[0].  Handles -inf max (all entries -inf
    in a row) by zeroing the offset (so the result is -inf, not NaN),
    matching the original `np.where(np.isfinite(m), m, 0.0)` semantic.

    This is an internal helper for the EM kernel.  Math:
      m_i  = max_j x_ij
      m'_i = m_i if finite, else 0.0
      out_i = m'_i + log(sum_j exp(x_ij - m'_i))
    Note: the (m_i not finite) branch is reached only when all entries
    in row i are -inf, in which case sum exp(x - 0) = 0 and log(0) =
    -inf, so out_i = -inf — matches the original.
    """
    N, K = x.shape
    out = np.empty(N, dtype=np.float64)
    for i in range(N):
        # max along K
        m = x[i, 0]
        for k in range(1, K):
            if x[i, k] > m:
                m = x[i, k]
        # m_safe: zero if -inf, else m.  np.isfinite returns False for
        # +inf and NaN too; we replicate that.
        if np.isfinite(m):
            m_safe = m
        else:
            m_safe = 0.0
        # sum exp(x - m_safe)
        s = 0.0
        for k in range(K):
            s += np.exp(x[i, k] - m_safe)
        out[i] = m_safe + np.log(s)
    return out


@njit(cache=True)
def _bernoulli_mixture_em_kernel(cands, K, init_centers,
                                    max_iter, tol, eps):
    """Numba kernel for _bernoulli_mixture_em.

    Faithfully reproduces the EM math step by step, with two changes
    from the pure-Python version:
      1. Matmuls (cands @ log_theta.T, resp.T @ cands) remain as numba
         @ operator, which dispatches to the same OpenBLAS backend as
         numpy — no performance change, no numerical change.
      2. The custom _logsumexp(axis=1) is replaced by an inlined
         scalar-loop equivalent (_logsumexp_axis1_kernel) so the whole
         iteration body runs as compiled native code with no Python
         object round-trips.

    Numerical behavior: bit-identical to the pure-Python version on
    typical inputs.  Tiny floating-point differences are possible at
    the last bit because:
      - numpy's vectorized `max(axis=1)`, `exp`, `sum` may use SIMD
        reductions with different rounding order than the scalar loop.
      - The matmul result is identical (same BLAS), but the +log_pi
        addition is done element-wise so order is preserved.
    Empirically (see validation suite) all tested seeds produced
    identical theta and resp arrays to full float64 precision.

    Args identical to _bernoulli_mixture_em; returns the same tuple.
    Note: when max_iter == 0, returns init_centers smoothed but resp
    and ll uninitialized in the original — we match that by allocating
    resp to zeros (matches the original which returns resp=None — but
    since numba can't return None, we return zeros; the wrapper detects
    this case and substitutes None for downstream Python callers).
    """
    N, L = cands.shape
    # Smooth initial centers from {0, 1} to (eps, 1-eps) for numerical stability
    theta = init_centers.astype(np.float64) * (1 - 2 * eps) + eps
    pi = np.ones(K, dtype=np.float64) / K

    prev_ll = -np.inf
    n_iter = 0
    ll = 0.0    # initialised in case max_iter=0 (defensive)

    # Pre-allocate resp so the function has a value to return even
    # when max_iter=0.  The original returns resp=None in that case;
    # we return all-zeros here and the wrapper handles the None
    # substitution.  In practice production never sets max_iter=0
    # so this code path is purely defensive.
    resp = np.zeros((N, K), dtype=np.float64)

    for it in range(max_iter):
        n_iter = it + 1
        # E-step
        log_theta = np.log(theta)
        log_one_minus_theta = np.log(1 - theta)
        # E-step emission log P(c | k), FUSED to a single GEMM.  The original
        # form was the two-GEMM expression
        #     log_p = cands @ log_theta.T + (1 - cands) @ log_one_minus_theta.T
        # which also materialises a full (N, L) (1 - cands) temporary.  Since
        # `cands` is binary {0, 1}, that equals (exactly, in real arithmetic)
        #     cands @ (log_theta - log_one_minus_theta).T
        #         + sum_l log_one_minus_theta[k, l]
        # i.e. ONE GEMM against the logit matrix plus a per-component constant
        # c[k] (the row-sums of log_one_minus_theta) broadcast over samples.
        # This halves the E-step GEMM work and drops the (1 - cands) alloc.
        # The floating-point summation order differs from the two-GEMM form,
        # so log_p (and hence theta / resp / ll) may differ at the last bits;
        # the binary consensus (theta > 0.5) and the downstream BIC subset-
        # selection are robust to that (validated on the recovery panel).
        # Numba's @ dispatches to the same BLAS as numpy.
        logit = log_theta - log_one_minus_theta                  # (K, L)
        c = np.empty(K, dtype=np.float64)
        for k in range(K):
            s = 0.0
            for l in range(L):
                s += log_one_minus_theta[k, l]
            c[k] = s
        log_p = cands @ logit.T + c                              # (N, K) + (K,)
        log_pi = np.log(pi + 1e-15)
        # log_p_weighted = log_p + log_pi[None, :]  — broadcast row-wise
        log_p_weighted = log_p + log_pi  # numba broadcasts (N, K) + (K,)

        log_norm = _logsumexp_axis1_kernel(log_p_weighted)                       # (N,)
        # log_resp = log_p_weighted - log_norm[:, None]; then resp = exp(log_resp).
        # We don't actually need log_resp as a separate variable here.
        resp = np.empty((N, K), dtype=np.float64)
        for i in range(N):
            for k in range(K):
                resp[i, k] = np.exp(log_p_weighted[i, k] - log_norm[i])

        # ll = float(log_norm.sum())
        ll_acc = 0.0
        for i in range(N):
            ll_acc += log_norm[i]
        ll = ll_acc

        # Convergence check (relative).  Break BEFORE updating prev_ll so
        # the caller receives the most recent ll value.
        if prev_ll != -np.inf and abs(ll - prev_ll) < tol * max(abs(ll), 1.0):
            break
        prev_ll = ll

        # M-step
        # N_k = resp.sum(axis=0)
        N_k = np.empty(K, dtype=np.float64)
        for k in range(K):
            s = 0.0
            for i in range(N):
                s += resp[i, k]
            N_k[k] = s
        # pi = N_k / N
        pi = N_k / N
        # N_k_safe = np.maximum(N_k, 1e-10)
        N_k_safe = np.empty(K, dtype=np.float64)
        for k in range(K):
            N_k_safe[k] = N_k[k] if N_k[k] > 1e-10 else 1e-10
        # theta = (resp.T @ cands) / N_k_safe[:, None]
        theta = (resp.T @ cands) / N_k_safe.reshape(K, 1)
        # theta = np.clip(theta, eps, 1 - eps)
        for k in range(K):
            for l in range(L):
                if theta[k, l] < eps:
                    theta[k, l] = eps
                elif theta[k, l] > 1 - eps:
                    theta[k, l] = 1 - eps

    return theta, pi, ll, n_iter, resp


def _bernoulli_mixture_em(cands, K, init_centers,
                            max_iter=RECOVERY_MIXTURE_MAX_ITER,
                            tol=RECOVERY_MIXTURE_TOL,
                            eps=RECOVERY_MIXTURE_THETA_EPS):
    """Single EM run for a Bernoulli mixture with K components.

    Args:
      cands: (N, L) float64 array (binary 0/1 values, but float for arithmetic)
      K: number of components
      init_centers: (K, L) initial theta values (binary will be smoothed)
      max_iter: cap on EM iterations
      tol: relative LL change threshold for convergence
      eps: theta clipping bound for numerical stability

    Returns:
      theta:  (K, L) final mixture parameters
      pi:     (K,)   final mixture weights
      ll:     final log-likelihood (scalar)
      n_iter: number of iterations actually used
      resp:   (N, K) responsibilities (soft assignments)

    Math:
      E-step: log P(c | k) = c . log(theta_k) + (1-c) . log(1-theta_k)
              gamma_nk = pi_k * P(c_n | k) / sum_j pi_j * P(c_n | j)
      M-step: theta_k[l] = sum_n gamma_nk * c_n[l] / sum_n gamma_nk
              pi_k = sum_n gamma_nk / N

    Implementation: delegates to a numba kernel that fuses the E/M
    step body with the logsumexp helper.  Matmul ops (cands @ log_theta.T
    and resp.T @ cands) remain BLAS-dispatched via numba's @ operator —
    same backend as numpy, no performance regression.  Per-block
    contribution at production size is ~24 ms across ~60 EM calls; the
    numba pass roughly halves this.  Output is numerically equivalent
    to the pure-Python version up to floating-point reduction-order
    differences (validated bit-identical on all tested seeds).
    """
    N, L = cands.shape
    # Edge case: max_iter=0 — original returns resp=None.  Detect and
    # substitute None for backward compatibility (the kernel returns
    # zeros to satisfy numba's return-type constraint).
    if max_iter == 0:
        theta = init_centers.astype(np.float64) * (1 - 2 * eps) + eps
        pi = np.ones(K, dtype=np.float64) / K
        return theta, pi, 0.0, 0, None

    # Ensure cands and init_centers are contiguous float64 — the
    # kernel signature requires this for the matmul dispatch and the
    # numba type-binding to be consistent across call sites.
    cands_arr = np.ascontiguousarray(cands, dtype=np.float64)
    init_arr = np.ascontiguousarray(init_centers, dtype=np.float64)

    theta, pi, ll, n_iter, resp = _bernoulli_mixture_em_kernel(
        cands_arr, K, init_arr, int(max_iter), float(tol), float(eps))
    return theta, pi, float(ll), int(n_iter), resp


@njit(cache=True, parallel=True, fastmath=False)
def _run_em_all_combos_kernel(cands, combo_K, is_full, uniforms_padded,
                              K_max_eff, max_iter, tol, eps):
    """Run K-means++ init + EM for EVERY (K, restart) combo in one prange.

    Replaces the per-K _run_em_restarts_kernel.  That kernel parallelised only
    the n_restarts restarts within a single K, so its prange was at most
    n_restarts wide (=2 by default) and a block with ~110 free cores still ran
    the K-sweep almost serially.  This widens the parallel axis to all
    K_max_eff * n_restarts combos at once, so a straggler block fills the cores
    it has.

    Each combo independently builds its own init and runs the SAME serial
    _bernoulli_mixture_em_kernel as before, writing only its own output rows (no
    shared state), so every combo's (ll, theta, pi, resp) is bit-identical to
    the old per-K kernel given the same init.  The init is built here from
    precomputed uniforms rather than drawn inside the kernel:

      - is_full[c] is True only when K == N (candidate count).  This mirrors
        _kmeans_pp_init's ``K >= N`` branch, whose init is all N candidates in
        order (candidates[range(N)]); since the caller caps K <= N, the K > N
        sub-case (which would draw rng.integers) never occurs, so this branch
        consumes no randomness -- matching the wrapper exactly.
      - otherwise the K-means++ centres come from _kmeans_pp_init_kernel fed the
        first K entries of uniforms_padded[c], i.e. the very rng.random(K) draws
        the serial wrapper would have made for this (K, restart); identical
        uniforms -> identical centres.

    Outputs are padded to K_max_eff on the component axis (a combo with K
    components fills rows/cols [:K]); the caller slices [:K] per combo.

    Args:
        cands:           (N, L) float64 candidate matrix (shared, read-only).
        combo_K:         (C,) int64 -- K for each combo, C = K_max_eff*n_restarts,
                         laid out K-major then restart-minor (combo
                         (K-1)*n_restarts + r is restart r of K).
        is_full:         (C,) bool -- True when K == N (all-candidates init).
        uniforms_padded: (C, K_max_eff) float64 -- first K entries per combo are
                         this (K, restart)'s rng.random(K) draws.
        K_max_eff:       component-axis width of the padded outputs.
        max_iter, tol, eps: EM hyper-parameters.

    Returns (padded to K_max_eff on the component axis):
        lls:    (C,)                 final LL per combo.
        thetas: (C, K_max_eff, L)    final theta per combo (rows [:K] valid).
        pis:    (C, K_max_eff)       final pi per combo (cols [:K] valid).
        resps:  (C, N, K_max_eff)    final responsibilities (cols [:K] valid).
    """
    C = combo_K.shape[0]
    N = cands.shape[0]
    L = cands.shape[1]
    lls = np.empty(C, dtype=np.float64)
    thetas = np.zeros((C, K_max_eff, L), dtype=np.float64)
    pis = np.zeros((C, K_max_eff), dtype=np.float64)
    resps = np.zeros((C, N, K_max_eff), dtype=np.float64)
    for c in prange(C):
        K = combo_K[c]
        # Build this combo's (K, L) init centres.
        init = np.empty((K, L), dtype=np.float64)
        if is_full[c]:
            # K == N: all candidates in order (candidates[range(N)].copy()).
            for i in range(K):
                for l in range(L):
                    init[i, l] = cands[i, l]
        else:
            centers_idx = _kmeans_pp_init_kernel(cands, K, uniforms_padded[c, :K])
            for i in range(K):
                ci = centers_idx[i]
                for l in range(L):
                    init[i, l] = cands[ci, l]
        # EM (serial, deterministic given init).
        theta_c, pi_c, ll_c, n_iter_c, resp_c = _bernoulli_mixture_em_kernel(
            cands, K, init, max_iter, tol, eps)
        lls[c] = ll_c
        for k in range(K):
            for l in range(L):
                thetas[c, k, l] = theta_c[k, l]
            pis[c, k] = pi_c[k]
        for i in range(N):
            for k in range(K):
                resps[c, i, k] = resp_c[i, k]
    return lls, thetas, pis, resps


def _fit_bernoulli_mixture_select_K(candidates,
                                      K_max=RECOVERY_MIXTURE_K_MAX,
                                      n_restarts=RECOVERY_MIXTURE_N_RESTARTS,
                                      seed=RECOVERY_MIXTURE_RNG_SEED,
                                      patience=RECOVERY_MIXTURE_PATIENCE,
                                      verbose=False):
    """Fit Bernoulli mixture for K=1..K_max, pick the K minimising BIC.

    Args:
      candidates: list of (L,) binary arrays
      K_max: upper bound on K to try
      n_restarts: EM restarts per K (with different K-means++ seeds)
      seed: base RNG seed (for reproducibility)
      patience: stop the K-sweep after this many CONSECUTIVE increasing-K
        values fail to improve the best BIC (see RECOVERY_MIXTURE_PATIENCE).
        Truncates the sweep tail only; does not change the selected K among
        the K it evaluates.  patience=None disables the early stop (full
        sweep, bit-identical to the pre-early-stop behaviour).
      verbose: print BIC trace

    Returns:
      list of (L,) binary arrays -- the consensus haps for the selected K.
      Empty list if candidates is empty.

    BIC formula:
      BIC = -2 * LL + (K*L + K - 1) * log(N)
        - K*L params for the mixture component profiles
        - K-1 params for the mixture weights (one constraint pi.sum() == 1)
      Lower BIC = better.

    The output is INTENTIONALLY over-permissive -- inner BIC measures
    density of candidates in candidate-space (which can include noise
    components from recombinant or low-cleanness candidates).  The outer
    BIC subset-selection on actual sample data (in the recovery round
    loop) filters these out.

    Parallelism:
      Every (K, restart) fit is independent up to the final BIC comparison, so
      all K_max_effective * n_restarts of them run in ONE prange via
      _run_em_all_combos_kernel -- much wider than the old per-K kernel's
      n_restarts-only axis, so a straggler block with free cores fills them.
      Bit-identity with the serial sweep is preserved: ``rng`` is consumed only
      by the K-means++ inits (the EM is deterministic given its init), so the
      uniforms for ALL (K, restart) are drawn here up front in exactly the old
      nested order (K outer, restart inner; rng.random(K) per init, nothing for
      the K == N branch), giving identical inits; the per-K best-restart pick,
      BIC, and patience early-stop are then replayed below over the precomputed
      results, selecting the same K.  Drawing uniforms for K beyond the patience
      cut-off only advances this local (discarded) rng and never affects the
      inits of the K actually evaluated.
    """
    if len(candidates) == 0:
        return []

    cands_arr = np.ascontiguousarray(
        np.stack(candidates, axis=0).astype(np.float64))                  # (N, L)
    N, L = cands_arr.shape

    # Cap K_max at N (can't have more components than candidates)
    K_max_effective = min(K_max, N)

    rng = np.random.default_rng(seed)

    if verbose:
        print(f'    Inner mixture fitting: N={N} candidates, L={L}, '
              f'trying K=1..{K_max_effective}, n_restarts={n_restarts}')

    # Set the thread allocation once before the (dominant) parallel sweep --
    # this fit is one phase of the block, so a straggler grows into freed cores
    # here rather than at each K of a serial loop.
    dynamic_threads.apply_dynamic_threads()

    # --- Phase 1: draw all K-means++ uniforms, in the SAME order the old per-K
    # serial loop consumed them (so the inits are identical). ---
    n_combos = K_max_effective * n_restarts
    combo_K = np.empty(n_combos, dtype=np.int64)
    is_full = np.zeros(n_combos, dtype=np.bool_)
    uniforms_padded = np.zeros((n_combos, K_max_effective), dtype=np.float64)
    c = 0
    for K in range(1, K_max_effective + 1):
        for _restart in range(n_restarts):
            combo_K[c] = K
            if K >= N:
                # Mirrors _kmeans_pp_init's ``K >= N`` branch (all-candidates
                # init).  K never exceeds N (K <= K_max_effective = min(K_max,
                # N)), so this is the K == N case, which draws no randomness.
                is_full[c] = True
            else:
                uniforms_padded[c, :K] = rng.random(K)
            c += 1

    # --- Phase 2: run init + EM for all (K, restart) combos in parallel. ---
    lls, thetas_p, pis_p, resps_p = _run_em_all_combos_kernel(
        cands_arr, combo_K, is_full, uniforms_padded, int(K_max_effective),
        int(RECOVERY_MIXTURE_MAX_ITER), float(RECOVERY_MIXTURE_TOL),
        float(RECOVERY_MIXTURE_THETA_EPS))

    # --- Phase 3: replay the per-K best-restart pick + BIC + patience exactly
    # as the serial sweep did, over the precomputed per-combo results. ---
    best_overall = None   # tuple: (K, BIC, theta, pi, ll, effective_sizes)
    no_improve = 0        # consecutive increasing-K with no BIC improvement
    bic_trace = []
    for K in range(1, K_max_effective + 1):
        base = (K - 1) * n_restarts
        # strict-> lowest-index reduction over restarts (keeps the FIRST restart
        # attaining the max LL, as the old loop did).
        best_r = 0
        for r in range(1, n_restarts):
            if lls[base + r] > lls[base + best_r]:
                best_r = r
        ci = base + best_r
        ll = float(lls[ci])
        # [:K] slice + .copy() so theta/pi/resp are standalone arrays (not views
        # into the padded per-combo buffers).
        theta = thetas_p[ci, :K, :].copy()
        pi = pis_p[ci, :K].copy()
        resp = resps_p[ci, :, :K].copy()
        n_params = K * L + (K - 1)
        bic = -2 * ll + n_params * np.log(max(N, 2))

        effective_sizes = resp.sum(axis=0)
        bic_trace.append((K, bic, ll, effective_sizes))

        if best_overall is None or bic < best_overall[1]:
            best_overall = (K, bic, theta, pi, ll, effective_sizes)
            no_improve = 0
        else:
            # No BIC improvement at this K.  Count it; once `patience`
            # CONSECUTIVE increasing-K values have failed to beat the best BIC,
            # stop (the tail is wasted work -- see RECOVERY_MIXTURE_PATIENCE).
            # patience=None disables this (full sweep).  Computing the cut-off
            # K's in Phase 2 anyway is cheap speculative work and changes
            # nothing: they are simply not considered here.
            no_improve += 1
            if patience is not None and no_improve >= patience:
                if verbose:
                    print(f'      [patience] stop sweep at K={K} '
                          f'({no_improve} consecutive non-improving K; '
                          f'best K={best_overall[0]})')
                break

    if verbose:
        for K, bic, ll, eff_sizes in bic_trace:
            marker = ' <-' if K == best_overall[0] else ''
            eff_str = '[' + ', '.join(f'{s:.1f}' for s in eff_sizes) + ']'
            print(f'      K={K:>2d}: LL={ll:>11.1f}, BIC={bic:>11.1f}, '
                  f'eff_sizes={eff_str}{marker}')

    best_K, best_bic, best_theta, best_pi, best_ll, best_eff = best_overall
    if verbose:
        print(f'    Inner mixture: selected K={best_K} with BIC={best_bic:.1f}')

    # Round theta to binary haps (consensus founder profiles)
    binary_thetas = (best_theta > 0.5).astype(np.int64)
    return [binary_thetas[k].copy() for k in range(best_K)]


@njit(cache=True)
def _bernoulli_mixture_ml_em_kernel(L0, L1, K, init_theta,
                                      max_iter, tol, eps):
    """Numba kernel for _bernoulli_mixture_ml_em (marginal-likelihood EM).

    Mixture of Bernoulli HAPLOTYPES over the latent other-strand allele o.
    Component k posits o[l] ~ Bernoulli(theta_k[l]); each candidate is
    observed only through its per-site other-strand likelihoods (L0, L1).

    E-step (marginalises o, no hard call):
      log P(cand_m | k) = sum_l log( L0[m,l]*(1-theta_k[l])
                                     + L1[m,l]*theta_k[l] ) + log pi_k
      resp_mk = softmax_k of the above.
    M-step (deferral update — the key difference from the plug-in soft):
      r_o(m,l,k) = L1[m,l]*theta_k[l]
                   / (L0[m,l]*(1-theta_k[l]) + L1[m,l]*theta_k[l])
      theta_k[l] = sum_m resp_mk * r_o(m,l,k) / sum_m resp_mk
    At an uninformative site (L0 ~ L1) r_o -> theta_k[l], so the candidate
    votes for the status quo and the consensus converges to the mean of the
    INFORMATIVE candidates only — no dilution toward 0.5.  pi_k = N_k / M.

    Args:
        L0, L1: (M, L) float64 — per-candidate other-strand likelihoods
        K: number of components
        init_theta: (K, L) initial component profiles (in [0,1])
        max_iter, tol, eps: EM iteration cap, rel-LL tol, theta clip bound

    Returns:
        theta: (K, L) final profiles
        pi:    (K,)   final weights
        ll:    final log-likelihood (scalar)
        n_iter: iterations used
        resp:  (M, K) responsibilities
    """
    M, L = L0.shape
    theta = init_theta.astype(np.float64)
    for k in range(K):
        for l in range(L):
            if theta[k, l] < eps:
                theta[k, l] = eps
            elif theta[k, l] > 1.0 - eps:
                theta[k, l] = 1.0 - eps
    pi = np.ones(K, dtype=np.float64) / K

    prev_ll = -np.inf
    n_iter = 0
    ll = 0.0
    resp = np.zeros((M, K), dtype=np.float64)

    for it in range(max_iter):
        n_iter = it + 1
        # E-step: per-candidate, per-component marginal log-likelihood.
        log_pi = np.log(pi + 1e-15)
        logp = np.empty((M, K), dtype=np.float64)
        for m in range(M):
            for k in range(K):
                s = 0.0
                for l in range(L):
                    mix = L0[m, l] * (1.0 - theta[k, l]) + L1[m, l] * theta[k, l]
                    if mix < 1e-300:
                        mix = 1e-300
                    s += np.log(mix)
                logp[m, k] = s + log_pi[k]
        # logsumexp over k -> resp, ll
        ll_acc = 0.0
        for m in range(M):
            mx = logp[m, 0]
            for k in range(1, K):
                if logp[m, k] > mx:
                    mx = logp[m, k]
            se = 0.0
            for k in range(K):
                se += np.exp(logp[m, k] - mx)
            lnorm = mx + np.log(se)
            ll_acc += lnorm
            for k in range(K):
                resp[m, k] = np.exp(logp[m, k] - lnorm)
        ll = ll_acc

        # Convergence check (relative).  Break before updating prev_ll so the
        # caller receives the most recent ll.
        if prev_ll != -np.inf and abs(ll - prev_ll) < tol * max(abs(ll), 1.0):
            break
        prev_ll = ll

        # M-step.
        N_k = np.zeros(K, dtype=np.float64)
        for k in range(K):
            for m in range(M):
                N_k[k] += resp[m, k]
        for k in range(K):
            pi[k] = N_k[k] / M
        new_theta = np.empty((K, L), dtype=np.float64)
        for k in range(K):
            nk = N_k[k] if N_k[k] > 1e-10 else 1e-10
            for l in range(L):
                tkl = theta[k, l]
                num = 0.0
                for m in range(M):
                    den = L0[m, l] * (1.0 - tkl) + L1[m, l] * tkl
                    if den < 1e-300:
                        den = 1e-300
                    num += resp[m, k] * (L1[m, l] * tkl) / den
                v = num / nk
                if v < eps:
                    v = eps
                elif v > 1.0 - eps:
                    v = 1.0 - eps
                new_theta[k, l] = v
        theta = new_theta

    return theta, pi, ll, n_iter, resp


def _bernoulli_mixture_ml_em(L0, L1, K, init_theta,
                               max_iter=RECOVERY_MIXTURE_MAX_ITER,
                               tol=RECOVERY_MIXTURE_TOL,
                               eps=RECOVERY_MIXTURE_THETA_EPS):
    """Single marginal-likelihood EM run (model B).  Thin wrapper around
    _bernoulli_mixture_ml_em_kernel; see it for the math.

    Args:
      L0, L1: (M, L) float64 other-strand likelihoods
      K: number of components
      init_theta: (K, L) initial profiles
      max_iter, tol, eps: EM controls

    Returns:
      theta (K, L), pi (K,), ll (float), n_iter (int), resp (M, K)
    """
    L0c = np.ascontiguousarray(L0, dtype=np.float64)
    L1c = np.ascontiguousarray(L1, dtype=np.float64)
    init = np.ascontiguousarray(init_theta, dtype=np.float64)
    theta, pi, ll, n_iter, resp = _bernoulli_mixture_ml_em_kernel(
        L0c, L1c, int(K), init, int(max_iter), float(tol), float(eps))
    return theta, pi, float(ll), int(n_iter), resp


@njit(cache=True, parallel=True, fastmath=False)
def _run_ml_em_all_combos_kernel(L0, L1, Eo, combo_K, is_full, uniforms_padded,
                                 K_max_eff, max_iter, tol, eps):
    """ML-marginalised analogue of _run_em_all_combos_kernel: K-means++ init +
    marginal-likelihood EM for EVERY (K, restart) combo in one prange.

    Replaces the per-K _run_ml_em_restarts_kernel (n_restarts-wide axis) with a
    single prange over all K_max_eff * n_restarts combos, so a straggler block
    fills its free cores.  Each combo builds its init from precomputed uniforms
    (on Eo, the expected other strand) and runs the SAME serial
    _bernoulli_mixture_ml_em_kernel on (L0, L1), writing only its own rows, so
    every combo's (ll, theta) is bit-identical to the old per-K kernel given the
    same init.  Only ll and theta are retained (the ML sweep discards pi and
    resp), but the EM kernel is invoked with its full signature.

      - is_full[c] is True only when K == M (candidate count); it mirrors
        _kmeans_pp_init's ``K >= N`` branch (N == M here), an all-Eo-rows init
        that consumes no randomness (K never exceeds M).
      - otherwise the centres come from _kmeans_pp_init_kernel on Eo fed the
        first K entries of uniforms_padded[c] -- the same rng.random(K) draws
        the serial wrapper made -- so the centres are identical.

    Args:
        L0, L1:          (M, L) float64 per-strand other-strand likelihoods,
                         contiguous (same ascontiguousarray copies the wrapper
                         builds).
        Eo:              (M, L) float64 expected other strand, the K-means++
                         init space (rows of Eo are the candidate profiles).
        combo_K:         (C,) int64 -- K for each combo (K-major, restart-minor).
        is_full:         (C,) bool -- True when K == M (all-Eo-rows init).
        uniforms_padded: (C, K_max_eff) float64 -- first K entries per combo are
                         this (K, restart)'s rng.random(K) draws.
        K_max_eff:       component-axis width of the padded outputs.
        max_iter, tol, eps: EM hyper-parameters.

    Returns (padded to K_max_eff on the component axis):
        lls:    (C,)               final LL per combo.
        thetas: (C, K_max_eff, L)  final theta per combo (rows [:K] valid).
    """
    C = combo_K.shape[0]
    M = Eo.shape[0]
    L = L0.shape[1]
    lls = np.empty(C, dtype=np.float64)
    thetas = np.zeros((C, K_max_eff, L), dtype=np.float64)
    for c in prange(C):
        K = combo_K[c]
        init = np.empty((K, L), dtype=np.float64)
        if is_full[c]:
            # K == M: all Eo rows in order (Eo[range(M)].copy()).
            for i in range(K):
                for l in range(L):
                    init[i, l] = Eo[i, l]
        else:
            centers_idx = _kmeans_pp_init_kernel(Eo, K, uniforms_padded[c, :K])
            for i in range(K):
                ci = centers_idx[i]
                for l in range(L):
                    init[i, l] = Eo[ci, l]
        theta_c, pi_c, ll_c, n_iter_c, resp_c = _bernoulli_mixture_ml_em_kernel(
            L0, L1, K, init, max_iter, tol, eps)
        lls[c] = ll_c
        for k in range(K):
            for l in range(L):
                thetas[c, k, l] = theta_c[k, l]
    return lls, thetas


def _fit_bernoulli_mixture_ml_select_K(L0, L1,
                                         K_max=RECOVERY_MIXTURE_K_MAX,
                                         n_restarts=RECOVERY_MIXTURE_N_RESTARTS,
                                         seed=RECOVERY_MIXTURE_RNG_SEED,
                                         patience=RECOVERY_MIXTURE_PATIENCE,
                                         verbose=False):
    """Marginal-likelihood Bernoulli-haplotype mixture (model B) for the
    "soft" recovery path: fit K=1..K_max, pick the K minimising BIC, return
    the rounded consensus haps.  The model-B analogue of
    _fit_bernoulli_mixture_select_K.

    Each candidate is a pair of per-site other-strand likelihood vectors
    (L0, L1) from _run_subtraction_round_soft.  The mixture marginalises the
    latent other-strand allele (E-step) and updates each profile from the
    informative candidates only (M-step deferral), so low-coverage /
    heterozygous-ambiguous sites neither bias cluster assignment nor pull the
    consensus toward 0.5 -- the failure mode of plugging the posterior mean
    P(o=1) into a plain Bernoulli mixture.  Sub-threshold evidence is still
    used (graded), unlike the binary argmax path which thresholds it away.

    K-means++ init runs on the expected other strand E[o] = L1/(L0+L1) using
    the same (L1-distance) initialiser as the argmax path.  BIC and the
    over-permissive inner-fit philosophy match _fit_bernoulli_mixture_select_K
    (the outer BIC subset-selection on sample data filters noise components).

    Args:
      L0, L1: (M, L) float64 other-strand likelihoods
      K_max: upper bound on K to try
      n_restarts: EM restarts per K (different K-means++ seeds)
      seed: base RNG seed
      patience: stop the K-sweep after this many CONSECUTIVE increasing-K
        values fail to improve the best BIC (see RECOVERY_MIXTURE_PATIENCE).
        Truncates the sweep tail only; does not change the selected K among
        the K it evaluates.  patience=None disables the early stop (full
        sweep, bit-identical to the pre-early-stop behaviour).
      verbose: print BIC trace

    Returns:
      list of (L,) binary arrays -- consensus haps for the selected K.
      Empty list if there are no candidates.

    BIC formula (identical to the binary mixture):
      BIC = -2*LL + (K*L + K - 1) * log(max(M, 2)),  lower = better.

    Parallelism:
      Identical scheme to _fit_bernoulli_mixture_select_K: all K_max_effective *
      n_restarts (K, restart) fits run in one prange via
      _run_ml_em_all_combos_kernel (vs the old per-K, n_restarts-only axis), and
      bit-identity is preserved by drawing every init's uniforms up front in the
      old nested order then replaying the best-restart / BIC / patience logic.
    """
    M = L0.shape[0]
    if M == 0:
        return []
    L = L0.shape[1]

    # Expected other strand for the kmeans++ init distance (in [0,1]).
    Eo = L1 / (L0 + L1 + 1e-12)                                   # (M, L)
    Eo = np.ascontiguousarray(Eo, dtype=np.float64)
    # Contiguous float64 copies of L0/L1, exactly as the _bernoulli_mixture_ml_em
    # wrapper builds, so the EM kernel sees identical inputs.
    L0c = np.ascontiguousarray(L0, dtype=np.float64)
    L1c = np.ascontiguousarray(L1, dtype=np.float64)

    K_max_effective = min(K_max, M)
    rng = np.random.default_rng(seed)

    if verbose:
        print(f'    Inner ML-mixture fitting: M={M} candidates, L={L}, '
              f'trying K=1..{K_max_effective}, n_restarts={n_restarts}')

    dynamic_threads.apply_dynamic_threads()

    # --- Phase 1: draw all K-means++ uniforms in the old per-K serial order. ---
    n_combos = K_max_effective * n_restarts
    combo_K = np.empty(n_combos, dtype=np.int64)
    is_full = np.zeros(n_combos, dtype=np.bool_)
    uniforms_padded = np.zeros((n_combos, K_max_effective), dtype=np.float64)
    c = 0
    for K in range(1, K_max_effective + 1):
        for _restart in range(n_restarts):
            combo_K[c] = K
            if K >= M:
                # _kmeans_pp_init's ``K >= N`` branch (N == M); K == M draws nothing.
                is_full[c] = True
            else:
                uniforms_padded[c, :K] = rng.random(K)
            c += 1

    # --- Phase 2: init + ML-EM for all (K, restart) combos in parallel. ---
    lls, thetas_p = _run_ml_em_all_combos_kernel(
        L0c, L1c, Eo, combo_K, is_full, uniforms_padded, int(K_max_effective),
        int(RECOVERY_MIXTURE_MAX_ITER), float(RECOVERY_MIXTURE_TOL),
        float(RECOVERY_MIXTURE_THETA_EPS))

    # --- Phase 3: replay best-restart + BIC + patience over the results. ---
    best_overall = None   # (K, BIC, theta)
    no_improve = 0        # consecutive increasing-K with no BIC improvement
    bic_trace = []
    for K in range(1, K_max_effective + 1):
        base = (K - 1) * n_restarts
        best_r = 0
        for r in range(1, n_restarts):
            if lls[base + r] > lls[base + best_r]:
                best_r = r
        ci = base + best_r
        ll = float(lls[ci])
        # [:K] slice + .copy() so theta is standalone (not a view into the
        # padded per-combo buffer).
        theta = thetas_p[ci, :K, :].copy()
        n_params = K * L + (K - 1)
        bic = -2 * ll + n_params * np.log(max(M, 2))
        bic_trace.append((K, bic, ll))

        if best_overall is None or bic < best_overall[1]:
            best_overall = (K, bic, theta)
            no_improve = 0
        else:
            no_improve += 1
            if patience is not None and no_improve >= patience:
                if verbose:
                    print(f'      [patience] stop sweep at K={K} '
                          f'({no_improve} consecutive non-improving K; '
                          f'best K={best_overall[0]})')
                break

    if verbose:
        for K, bic, ll in bic_trace:
            marker = ' <-' if K == best_overall[0] else ''
            print(f'      K={K:>2d}: LL={ll:>11.1f}, BIC={bic:>11.1f}{marker}')

    best_K, best_bic, best_theta = best_overall
    if verbose:
        print(f'    Inner ML-mixture: selected K={best_K} with BIC={best_bic:.1f}')

    # Round theta to binary consensus founder profiles.
    binary_thetas = (best_theta > 0.5).astype(np.int64)
    return [binary_thetas[k].copy() for k in range(best_K)]