"""Prepared, allocation-reusing forward scores for normalized diploid paths.

Validate observed GLs and construct data-only emissions once per block, not
once per trial panel. Ordered diploid states, unequal founder frequencies,
the independent unrepresented-allele state and likelihood normalization match
path_model. No fastmath, state pruning, frequency tying or model approximation.
"""
import numpy as np
from numba import njit, prange, get_num_threads
from . import path_model as reference


@njit(cache=True, parallel=True)
def _emissions(gl, observed):
    n, length = observed.shape
    output = np.empty((n, length, 3, 3))
    for sample in prange(n):
        for site in range(length):
            for a in range(3):
                for b in range(3):
                    output[sample, site, a, b] = (
                        reference._emission(a if a < 2 else -1,
                                            b if b < 2 else -1, gl[sample, site])
                        if observed[sample, site] else 1.)
    return output


def prepare_observations(gl, observed, positions, *, generations=3.,
                         recombination_rate_per_bp=5e-8, wildcard_mass=.01,
                         interval_morgans=None):
    """Prepare normalized GL emissions and genetic redraw rates once per block.

    Positions are in base pairs, recombination_rate_per_bp in Morgans/base pair,
    and generations multiplies the copying hazard. Explicit interval_morgans
    replaces position-derived intervals. Unobserved cells have neutral emission.
    """
    # Existing validation is performed at this block boundary. Search panels
    # are trusted binary candidates generated by the existing selector.
    dummy = np.zeros((1, np.asarray(gl).shape[1]), dtype=np.int64)
    _, gl, observed, _, rates = reference._prepare(
        dummy, gl, positions, observed, generations, recombination_rate_per_bp,
        wildcard_mass, interval_morgans, None)
    return dict(emissions=_emissions(gl, observed), rates=rates,
                wildcard_mass=wildcard_mass, gl=gl, observed=observed,
                positions=np.asarray(positions))


@njit(cache=True, parallel=True)
def _scores(alleles, pi, rates, emissions, workers):
    n, length, s = len(emissions), len(alleles), len(pi)
    result = np.empty(n)
    for worker_index in prange(workers):
        worker = np.int64(worker_index)
        filtered = np.empty((s, s))
        updated = np.empty((s, s))
        row, col = np.empty(s), np.empty(s)
        for sample in range(worker, n, workers):
            ll = 0.
            for site in range(length):
                if site:
                    row[:] = 0.
                    col[:] = 0.
                    for a in range(s):
                        for b in range(s):
                            row[a] += filtered[a, b]
                            col[b] += filtered[a, b]
                rate = rates[site-1] if site else 0.
                stay = 1. - rate
                scale = 0.
                for a in range(s):
                    ha = alleles[site, a]
                    for b in range(s):
                        hb = alleles[site, b]
                        prior = (stay * stay * filtered[a, b]
                            + stay * rate * (row[a] * pi[b] + pi[a] * col[b])
                            + rate * rate * pi[a] * pi[b]) if site else pi[a] * pi[b]
                        value = prior * emissions[sample, site, ha, hb]
                        updated[a, b] = value
                        scale += value
                if scale <= 0:
                    ll = -np.inf
                    break
                ll += np.log(scale)
                for a in range(s):
                    for b in range(s):
                        filtered[a, b] = updated[a, b] / scale
            result[sample] = ll
    return result


def score_prepared(panel, frequencies, prepared):
    """Score a trusted binary panel against the same prepared block observations."""
    k, length = panel.shape
    frequencies = np.asarray(frequencies, dtype=np.float64)
    frequencies = frequencies / frequencies.sum()
    pi = np.r_[(1-prepared['wildcard_mass'])*frequencies,
               prepared['wildcard_mass']]
    alleles = np.empty((length, k+1), dtype=np.int64)
    alleles[:, :k] = panel.T
    alleles[:, k] = 2
    values = _scores(alleles, pi, prepared['rates'], prepared['emissions'],
                     min(len(prepared['emissions']), get_num_threads()))
    return dict(log_likelihood=float(values.sum()), sample_log_likelihood=values,
                state_prior=pi, redraw_probabilities=prepared['rates'])


def score_panel(panel, gl, positions, observed_mask, *, generations=3.,
                recombination_rate_per_bp=5e-8, wildcard_mass=.01,
                interval_morgans=None, founder_frequencies=None):
    """Reference-compatible boundary for checks; search reuses preparation."""
    panel = np.asarray(panel, dtype=np.int64)
    prepared = prepare_observations(gl, observed_mask, positions,
        generations=generations, recombination_rate_per_bp=recombination_rate_per_bp,
        wildcard_mass=wildcard_mass, interval_morgans=interval_morgans)
    frequencies = np.ones(len(panel)) if founder_frequencies is None else founder_frequencies
    return score_prepared(panel, frequencies, prepared)
